# task: configure


- name: 'Install pip'
  apt:
    name: python-pip
    state: present

- name: 'Install docker-py'
  pip:
    name: docker-py
    state: present

- name: Log in
  shell: docker login -u {{ DOCKER_USERNAME }} -p {{ DOCKER_PASSWORD }}
  become: yes

- name: Up map count
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes

- name: Copy unit files
  copy: 
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0755
    owner: root
    group: root
  with_items:
    - "perforce"
    - "artifactory"
    - "mssql"

- name: Enable units
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - "perforce"
    - "artifactory"
    - "mssql"
