# task: configure

- name: Log into DockerHub
  docker_login:
    username: {{ DOCKER_USERNAME }}
    password: {{ DOCKER_PASSWORD }}

- name: Setup psql client libs
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - "postgresql-client-common"
    - "postgresql-client"

- name: Up map count
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes

- name: Copy unit files
  copy: 
    src: perforce.service 
    dest: /etc/systemd/system/perforce.service 
    mode: 0755
    owner: root
    group: root

- name: Enable units
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - "perforce"
