# jenkins-slave-windows.yml
# installs jenkins slave on windows

- name: Install multiple packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - directx
  - dotnetcore-sdk
  - jfrog-cli
  - jre8
  - javaruntime
  - kb2999226
  - python
  - unity-il2cpp
  - visualstudio2017professional
  - visualstudio2017-workload-nativedesktop

- name: Install P4 cli
  win_chocolatey:
    name: p4

- name: Copy Agent JAR file to connect to master
  win_copy:
    force: yes 
    src: agent.jar
    dest: C:\Program Files (x86)\Java\agent.jar

- name: Update PATH for Java
  win_environment:
    state: present
    name: JAVA_HOME
    value: C:\Program Files (x86)\Java\jre1.8.0_171\bin
    level: machine

- name: Run jar and connect to Jenkins master
  win_shell: java.exe -jar agent.jar -jnlpUrl http://{{ MASTER_IP }}:{{ MASTER_PORT }}/computer/{{ AGENT_NAME }}/slave-agent.jnlp
  args:
    chdir: C:\Program Files (x86)\Java\
 
