# jenkins-master-windows.yml
# installs jenkins master on windows

- name: Install multiple packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  #- android-sdk
  - directx
  - dotnetcore-sdk
  - git
  - jfrog-cli
  - jre8
  - javaruntime
  - jenkins
  - kb2999226
  - python
  - unity
  - unity-il2cpp
  - visualstudio2017professional
  - visualstudio2017-workload-nativedesktop

- name: Install P4 cli
  win_chocolatey:
    name: p4
    ignore_checksums: yes

- name: Create build directory
  win_file:
    path: C:\Jenkins\workspace
    state: directory

- name: Remove auto init password file
  win_file:
    force: yes
    path: C:\Program Files (x86)\Jenkins\secrets\initialAdminPassword
    state: absent

- name: Copy initPassword file to Jenkins Master instance
  win_copy:
    force: yes
    src: initialAdminPassword
    dest: C:\Program Files (x86)\Jenkins\secrets\initialAdminPassword

- name: Copy base config
  win_copy:
    force: yes
    src: config.xml
    dest: C:\Program Files (x86)\Jenkins\config.xml

- name: Copy pre approved scripts
  win_copy:
    force: yes
    src: scriptApproval.xml
    dest: C:\Program Files (x86)\Jenkins\scriptApproval.xml

- name: Create init.d groovy dir
  win_file:
    path: C:\Program Files (x86)\Jenkins\init.groovy.d
    state: directory

- name: Copy to init.d.groovy
  win_copy:
    force: yes
    src: init/a.groovy
    dest: C:\Program Files (x86)\Jenkins\init.groovy.d\a.groovy

- name: Copy to init.d.groovy
  win_copy:
    force: yes
    src: init/b.groovy
    dest: C:\Program Files (x86)\Jenkins\init.groovy.d\b.groovy

- name: Copy over jobs groovy to seed jobs
  win_copy:
    force: yes
    src: init/jobs.dsl
    dest: C:\Program Files (x86)\Jenkins\jobs.dsl

- name: Restart to pickup init password
  win_service:
    name: jenkins
    state: restarted

